### ISSUE TITLE
Some integration tests report events for other namespace

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#1001] opened 2022-09-30 14:44 UTC
## Description

Some integration tests report events for other namespace than the one dedicated to this test.

## Impact

As a consequence, the test fails because it except only one namespace to be printed.

## Environment and steps to reproduce

In ARO, the integration tests for `capabilities` and `biotop` fail because some events are printed for `test-tcptop-*` namespace:

* [`capabilities`](https://github.com/kinvolk/inspektor-gadget/actions/runs/3157606929/jobs/5140732930#step:6:22645):

```
2022-09-30T12:03:54.2901764Z     command.go:429: Stop command(StartCapabilitiesGadget)
2022-09-30T12:03:54.2902359Z     command.go:431: Command returned(StartCapabilitiesGadget):
2022-09-30T12:03:54.2902744Z         
2022-09-30T12:03:54.2904562Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-capabilities-2800655059608903620","pod":"test-pod","container":"test-pod","type":"normal","pid":2444819,"comm":"runc:[2:INIT]","cap":21,"capName":"CAP_SYS_ADMIN","verdict":"Allow","mountnsid":4026533142}
2022-09-30T12:03:54.2906846Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-capabilities-2800655059608903620","pod":"test-pod","container":"test-pod","type":"normal","pid":2444819,"comm":"runc:[2:INIT]","cap":21,"capName":"CAP_SYS_ADMIN","verdict":"Allow","mountnsid":4026533142}
2022-09-30T12:03:54.2909061Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-capabilities-2800655059608903620","pod":"test-pod","container":"test-pod","type":"normal","pid":2444819,"comm":"runc:[2:INIT]","cap":21,"capName":"CAP_SYS_ADMIN","verdict":"Allow","mountnsid":4026533142}
2022-09-30T12:03:54.2912397Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-capabilities-2800655059608903620","pod":"test-pod","container":"test-pod","type":"normal","pid":2444819,"comm":"runc:[2:INIT]","cap":21,"capName":"CAP_SYS_ADMIN","verdict":"Allow","mountnsid":4026533142}
2022-09-30T12:03:54.2915468Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-capabilities-2800655059608903620","pod":"test-pod","container":"test-pod","type":"normal","pid":2444819,"comm":"runc:[2:INIT]","cap":21,"capName":"CAP_SYS_ADMIN","verdict":"Allow","mountnsid":4026533142}
2022-09-30T12:03:54.2917667Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2444819,"comm":"runc:[2:INIT]","cap":21,"capName":"CAP_SYS_ADMIN","verdict":"Allow","mountnsid":4026533142}

```
* [`bindsnoop`](https://github.com/kinvolk/inspektor-gadget/actions/runs/3157606929/jobs/5140732930#step:6:22645):
```
2022-09-30T12:04:23.9869013Z     command.go:429: Stop command(StartBindsnoopGadget)
2022-09-30T12:04:23.9869342Z     command.go:431: Command returned(StartBindsnoopGadget):
2022-09-30T12:04:23.9869464Z         
2022-09-30T12:04:23.9871243Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473226,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9872938Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473243,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9874744Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473251,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9876482Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473302,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9878237Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473310,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9880051Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473335,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9881731Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473343,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9883424Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473351,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9885156Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473403,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9886826Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptop-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473420,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9888502Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473449,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9888628Z         
2022-09-30T12:04:23.9889197Z     command.go:440: invalid command output(StartBindsnoopGadget): verifying output with custom function: unexpected output entry:
2022-09-30T12:04:23.9889396Z           &types.Event{
2022-09-30T12:04:23.9889630Z           	Event: types.Event{
2022-09-30T12:04:23.9889962Z           		CommonData: types.CommonData{
2022-09-30T12:04:23.9890180Z           			Node:      "",
2022-09-30T12:04:23.9898127Z         - 			Namespace: "test-bindsnoop-5692438004181385183",
2022-09-30T12:04:23.9898742Z         + 			Namespace: "test-tcptop-2975123826752321008",
2022-09-30T12:04:23.9899093Z           			Pod:       "test-pod",
2022-09-30T12:04:23.9899429Z           			Container: "test-pod",
2022-09-30T12:04:23.9899592Z           		},
2022-09-30T12:04:23.9899828Z           		Type:    "normal",
2022-09-30T12:04:23.9900047Z           		Message: "",
2022-09-30T12:04:23.9900194Z           	},
2022-09-30T12:04:23.9900363Z           	Pid:  0,
2022-09-30T12:04:23.9900550Z           	Comm: "nc",
2022-09-30T12:04:23.9900804Z           	... // 6 identical fields
2022-09-30T12:04:23.9900943Z           }
```

## Expected behavior

Only the namespace for the given test should be printed.

**Comment by mauriciovasquezbernal** [comment] 2022-10-03 14:05
This is a difficult and weird one! 

I extracted some of the logs (I added some padding with `x` to align the columns):

bindnsoop:

```
2022-09-30T12:04:23.9871243Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473226,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9872938Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473243,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9874744Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473251,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9876482Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473302,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9878237Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473310,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9880051Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473335,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9881731Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473343,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9883424Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473351,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9885156Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473403,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9886826Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473420,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9888502Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473449,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9888628Z
```

capabilities:

```
2022-09-30T12:04:23.9871243Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473226,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9872938Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473243,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9874744Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473251,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9876482Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473302,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9878237Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473310,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9880051Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473335,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9881731Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473343,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9883424Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473351,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9885156Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473403,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9886826Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-tcptopxxx-2975123826752321008","pod":"test-pod","container":"test-pod","type":"normal","pid":2473420,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9888502Z         {"node":"arotestingcluster-kmcjg-worker-eastus2-nnb52","namespace":"test-bindsnoop-5692438004181385183","pod":"test-pod","container":"test-pod","type":"normal","pid":2473449,"comm":"nc","proto":"TCP","addr":"::","port":9090,"opts":".R...","mountnsid":4026533142}
2022-09-30T12:04:23.9888628Z
```

Things to notice:
- The generated events are all correct but the namespace is wrong (we can't say anything about pod and container because we use the same name for all tests). 
- The mount ns id of all events is the same (the issue is not in the eBPF filtering logic)
- I don't see anything relevant from the gadgets pods logs. (omitted here for brevity) 

It seems to me there is something wrong with the [`Enrich()`](https://github.com/kinvolk/inspektor-gadget/blob/3e9dd95366423b4ec28019fe78d7aa95fdfd2c83/pkg/gadgets/trace/bind/tracer/tracer.go#L307) logic. I'd say it's returning a bad container for some reason (a race condition?). 



I attach the file with the whole logs. (I trimmed a lot of duplicated lines without any extra info)
- [bindsnoop-fail.txt](https://github.com/kinvolk/inspektor-gadget/files/9698114/bindsnoop-fail.txt)
- [capabilities-fail.txt](https://github.com/kinvolk/inspektor-gadget/files/9698112/capabilities-fail.txt)
- [wrong-namespace-log.txt](https://github.com/kinvolk/inspektor-gadget/files/9698154/wrong-namespace-log.txt)

**Comment by blanquicet** [comment] 2022-11-24 12:10
It happened again. For the `TestExecsnoop` test:

Received event:
```bash
         {"node":"arotestingcluster-kmcjg-worker-eastus2-dl864","namespace":"openshift-operator-lifecycle-manager","pod":"collect-profiles-27821505-xznkk","container":"collect-profiles","type":"normal","pid":4058161,"ppid":4058148,"pcomm":"sh","args":["/bin/sh","-c","while true; do date ; sleep 0.1; done"],"mountnsid":4026533044}
```

Expected event:

```bash
     command.go:504: invalid command output(StartExecsnoopGadget): verifying output with custom function: output doesn't contain the expected entry: &{Event:{CommonData:{Node: Namespace:test-execsnoop-2278241010359639163 Pod:test-pod Container:test-pod} Type:normal Message:} Pid:0 Ppid:0 Comm:sh Retval:0 Args:[/bin/sh -c while true; do date ; sleep 0.1; done] UID:0 MountNsID:0}
```

**Comment by mauriciovasquezbernal** [comment] 2022-11-28 23:05
After many failed attempts I was able to reproduce it with local-gadget. 

Run this script in a terminal:

```bash
#! /bin/bash

while true
do
        docker run --rm --name we-broke-it ubuntu readlink /proc/self/ns/mnt &
        docker run --rm --name no-yet ubuntu cat /dev/null &

        for job in `jobs -p`
        do
        wait $job
        done
done
```

And then run local-gadget filtering only by the `no-yet` container:

```bash
$ sudo ./local-gadget trace exec -c no-yet
WARN[0000] Runtime enricher (cri-o): couldn't get current containers 
CONTAINER                                         PID        PPID       COMM             RET ARGS                                                             
[...]
# The following is messed up: It's from the `we-broke-it` container but was enriched with the no-yet one. 
no-yet                                            2289159    2289131    readlink         0   /usr/bin/readlink /proc/self/ns/mnt                              
[...]                                 
# This even comes from the we-broke-it event container
we-broke-it                                       2291416    2291356    readlink         0   /usr/bin/readlink /proc/self/ns/mnt                              
[...]
# this event comes from no-yet container but was enriched with we-broke-it (similar to what happened in this PR)                                        
we-broke-it                                       2292698    2292667    cat              0   /usr/bin/cat /dev/null                                           
```

So, what's going on? TL;DR: We have a race condition.

First of all, we have to remember that we use the mount namespace inode id to filter and enrich events, and that id is reused by the kernel. Then, all the issues above are caused because:

1. There is a delay to update the filtering map when a container is removed: this map could contain the mounts ns id of a container that was removed and at the same time a new container reusing the same mount ns id could be created, then the filtering mechanism will pick up events from the new container. 
2. It takes some time between capturing the event in the kernel and enriching in user space: it could happen that an event generated by the old container is enriched with data from the new one. 

I'll try to better understand if there is a feasible solution for it.

**Comment by mauriciovasquezbernal** [comment] 2022-12-02 23:02
I haven't been able to reproduce this exact same issue after https://github.com/inspektor-gadget/inspektor-gadget/pull/1160 was merged. I was able to reproduce a different issue: The container can be gone from the container collection by the time the tracer tries to enrich it.

1. Run the same script as above 
2. Stress one core on the CPU
```
$ taskset 0x4 stress-ng -c 1
```
3. Execute local-gadget bound to a single thread with the lowest priority 
```
$  sudo taskset 0x4 nice -20 ./local-gadget trace exec -c no-yet

...
no-yet                                            2443552    2443504    cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            2443812    2443773    cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            2444072    2444025    cat              0   /usr/bin/cat /dev/null                                           
                                                  2444333    2444289    cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            2444594    2444536    cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            2444854    2444793    cat              0   /usr/bin/cat /dev/null                                           
``` 

Some of the events miss the container data.

**Comment by mauriciovasquezbernal** [comment] 2023-06-22 16:41
I checked the CI logs and the first instance happened in https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5268597184/attempts/3#summary-14288281093, then it happens often:
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5278128887/attempts/2#summary-14287929215
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5268597184/attempts/3#summary-14288281093
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5279800219/attempts/1#summary-14292926432
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5282970208/attempts/1#summary-14302513683
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5282973077/attempts/1#summary-14303105248
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5283562090/attempts/1#summary-14304354154
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5289043463/attempts/1#summary-14318863164

Even if the outcome is the same as described when this issue was opened, the cause it totally different. TraceSni doesn't use the mount ns map to perform the filtering, it relies on the container collection package:

https://github.com/inspektor-gadget/inspektor-gadget/blob/829717b6a68d664ba3fc9c919638decc2495fd9f/pkg/operators/kubemanager/kubemanager.go#L279-L290

I think this regression was caused by https://github.com/inspektor-gadget/inspektor-gadget/pull/1430, however I still have some doubts:
- Why it only happens in ARO? (no in AKS or different minikube combinations we have)
- Why trace dns is not affected?

**Comment by alban** [comment] 2023-06-22 17:38
For most gadgets using mntns to enrich the container, the issue of mntns reusing by the kernel was resolved by keeping the mntns open (https://github.com/inspektor-gadget/inspektor-gadget/pull/1171). Should we also keep the netns open for the networking gadgets that use the netns to enrich events?

> Why it only happens in ARO? (no in AKS or different minikube combinations we have)

ARO uses the crio hook (`gadget-container/hooks/crio/gadget-prestart.json`) and I think the usual container-hook or runcfanotify packages are not used in that case. It runs this code:
https://github.com/inspektor-gadget/inspektor-gadget/blob/main/gadget-container/hooks/oci/main.go#L137

Could it be that it fails at some point, or sends the wrong information? Or it could fall back on the podinformer but too late, then the container data is changed in the middle of the test.

**Comment by alban** [comment] 2023-06-22 17:46
> ```diff
> Namespace: strings.Join({
> - 				"test-trace-sni-1291196847517858182",
> + 				"openshift-operator-lifecycle-manager",
> 			}, ""),
> - 			Pod:         "test-pod",
> + 			Pod:         "collect-profiles-28113840-4f5sl",
> ```

The `openshift-operator-lifecycle-manager/collect-profiles` is a job, so it is probably short lived. If the crio hooks are not working and we rely on the podinformer, it could be that IG still think the `collect-profiles` pod exists with a netns id that is reused by our `test-pod` pod.

**Comment by mauriciovasquezbernal** [comment] 2023-06-22 21:31
You almost nailed it! `openshift-operator-lifecycle-manager/collect-profiles` is a CronJob, when the pod terminates, its containers are reported as "Exited" and the post-stop hook isn't called (it's `post-stop`, so I think it's called when the container is actually removed). At this point, the container collection still thinks the container exists, but the network namespace inode is already gone and the operating system can reuse it for new containers. Hence, the enrichment by network namespace fails because it picks a wrong pod from the list.

> Why it only happens in ARO?

In ARO we use crio hooks and it seems pods from (Cron)Jobs aren't properly cleanup on this case.

How to fix it?

One possibility is to keep a reference to the network namespane inode to avoid it being reused. But I think we need to investigate why those containers are kept in the container collection when they are in an exited stated.

**Comment by alban** [comment] 2023-06-23 05:28
Now that we support crun, maybe we should remove the crio hook mode and use fanorify+ebpf.

**Comment by mauriciovasquezbernal** [comment] 2023-06-23 16:12
After going in a very deep rabbit hole, I know understand what's happening:
1. (https://github.com/inspektor-gadget/inspektor-gadget/pull/1780) The hooks in cri-o are working good. They are called when a container is created and when a container is **removed**. But there is a gotcha there. The stop hook is not called immediately when the container goes into Exited state, like the ones created by a Job or with `kubectl run --restart=Never --image busybox mypod -- sh -c "sleep 5 && echo foo"`, it takes some minutes for it to be called. To make things worse, the pod informer wasn't removing those containers either. So in the end, container collection was keeping a container with a net ns id that was released by the kernel and that was reused in new containers, making the enrichment to fail. 
2. (https://github.com/inspektor-gadget/inspektor-gadget/pull/1779)  We aren't keeping a reference of the net ns id to avoid the kernel to reuse it. 

Both issues combined create this issue. The real fix is https://github.com/inspektor-gadget/inspektor-gadget/pull/1779, however https://github.com/inspektor-gadget/inspektor-gadget/pull/1780 mitigates it as the window where the "exited" container is present in the container collection is smaller.

**Comment by mauriciovasquezbernal** [comment] 2023-06-23 16:18
> Now that we support crun, maybe we should remove the crio hook mode and use fanorify+ebpf.

Good point. I softly agree with that. IMO hooks are a much more reliable way to get notifications of containers being started / stopped. IIUC we developed podinformer, fanotify, etc. an extra mechanism when hooks weren't available. I agree that we can use fanotify+ebpf as a fallback mechanism here, but IMO we should look for and push for a standard hook mechanism like [NRI](https://github.com/containerd/nri) or similar.

**Closed** 2023-06-27 11:57 UTC
Labels: area/ci, k8s/aro
