### ISSUE TITLE
network-policy won't run on clusters with Fargate nodes

### ISSUE THREAD

**Issue by bcbrockway** [inspektor-gadget/inspektor-gadget#168] opened 2021-04-16 10:47 UTC
**Current situation**
We have a couple of Fargate nodes in our cluster in addition to the regular EC2 instances we want to monitor with the `network-policy` command. Fargate doesn't support network policies so I think there are two issues here:

1. That Inspektor Gadget applies a DaemonSet that doesn't exclude Fargate nodes
2. That it fails completely if it can't find all the daemons it expects:

```
$ kubectl gadget network-policy monitor --namespaces kube-node-lease,kube-public,kube-system,argocd --output ./networktrace.log
Error detected: "Error running command: \"Gadget Daemon not found\"\n"
Error running command: "Gadget Daemon not found"
Error running command: "Gadget Daemon not found"
Error running command: "Gadget Daemon not found"
Error running command: "Gadget Daemon not found"
Node ip-10-50-94-91.eu-west-1.compute.internal ready.
Node ip-10-50-82-156.eu-west-1.compute.internal ready.
```

**Impact**
We are unable to use the `network-policy` command.

**Ideal future situation**
The DaemonSet would not try to deploy on Fargate nodes and the `network-policy` command would exclude Fargate nodes from its list of required daemons.

**Implementation options**
The 1st issue should be fairly simple; you can just add an antiAffinity section to the DaemonSet:

```yaml
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
```

Not sure about the 2nd issue.

**Additional information**
[ Please Add any information that does not fit into any of the above sections here ]

**Comment by mauriciovasquezbernal** [comment] 2022-12-15 19:58
This should be fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1187. I'll close it. Feel free to reopen if the issue is still present.

**Closed by mauriciovasquezbernal** 2022-12-15 19:58 UTC
Labels: bug, gadget/network-policy, customer-issue
